/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "RX_1.h"
#include "RX_1_aliases.h"
#include "TX_1.h"
#include "TX_1_aliases.h"
#include "CAN.h"
#include "UART.h"
#include "UART_SPI_UART.h"
#include "UART_PINS.h"
#include "UART_SPI_UART_PVT.h"
#include "UART_PVT.h"
#include "UART_BOOT.h"
#include "CAN1_LED.h"
#include "CAN1_LED_aliases.h"
#include "CAN2_LED.h"
#include "CAN2_LED_aliases.h"
#include "Clock_1.h"
#include "blinker.h"
#include "Debug1_LED.h"
#include "Debug1_LED_aliases.h"
#include "Debug2_LED.h"
#include "Debug2_LED_aliases.h"
#include "Error1.h"
#include "Error1_aliases.h"
#include "Error2.h"
#include "Error2_aliases.h"
#include "CAN_isr.h"
#include "CAN_HFCLK.h"
#include "UART_SCBCLK.h"
#include "UART_tx.h"
#include "UART_tx_aliases.h"
#include "UART_rx.h"
#include "UART_rx_aliases.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

